# Generated by Django 2.0.3 on 2019-01-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_exam', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
