# Generated by Django 2.0.3 on 2019-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_subexam_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subexam',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
